{
 "title": "CPU_Memory_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100- (node_cpu_seconds_total{mode=\"idle\"} /1000)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"localhost:9100\"}*9.31 /10000000000",
     "legendFormat": "GB Available"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}*9.31 /10000000000",
     "legendFormat": "GB Free without cache"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{device=\"/dev/nvme0n1p1\",fstype=\"ext4\",mountpoint=\"/\"} )- (node_filesystem_avail_bytes{device=\"/dev/nvme0n1p1\",fstype=\"ext4\",mountpoint=\"/\"})) *9.31 /10000000000",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/nvme0n1p1\",fstype=\"ext4\",mountpoint=\"/\"} *9.31 /10000000000",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"localhost:9100\"}*9.31 /10000000000",
     "legendFormat": "Available (Free + Cache)"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}*9.31 /10000000000",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\"}*9.31 /10000000000",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"localhost:9100\"}*9.31 / 10000000000",
     "legendFormat": "Cache"
    }
   ]
  },
  {
   "title": "CPU All",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_cpu_seconds_total /1000", "legendFormat": "CPU {{cpu}} - {{mode}}" }
   ]
  }
 ]
}